tarot_deck = [
    {
        "id": "fool",
        "name_en": "The Fool",
        "name_tr": "Deli (Joker)",
        "meaning_upright_en": "New beginnings, innocence, spontaneity, a free spirit.",
        "meaning_upright_tr": "Yeni başlangıçlar, masumiyet, spontanlık, özgür ruh.",
        "meaning_reversed_en": "Recklessness, risk-taking, bad decisions.",
        "meaning_reversed_tr": "Dikkatsizlik, aşırı risk alma, kötü kararlar.",
        "element": "Air",
        "color": "#FFEB3B"
    },
    {
        "id": "magician",
        "name_en": "The Magician",
        "name_tr": "Büyücü",
        "meaning_upright_en": "Manifestation, resourcefulness, power, inspired action.",
        "meaning_upright_tr": "Tezahür, beceriklilik, güç, ilham verici eylem.",
        "meaning_reversed_en": "Manipulation, poor planning, untapped talents.",
        "meaning_reversed_tr": "Manipülasyon, kötü planlama, kullanılmayan yetenekler.",
        "element": "Air",
        "color": "#E91E63"
    },
    {
        "id": "high_priestess",
        "name_en": "The High Priestess",
        "name_tr": "Azize",
        "meaning_upright_en": "Intuition, sacred knowledge, divine feminine, the subconscious mind.",
        "meaning_upright_tr": "Sezgiler, kutsal bilgi, ilahi dişil, bilinçaltı.",
        "meaning_reversed_en": "Secrets, disconnected from intuition, withdrawal.",
        "meaning_reversed_tr": "Sırlar, sezgiden kopukluk, içine kapanma.",
        "element": "Water",
        "color": "#2196F3"
    },
    {
        "id": "empress",
        "name_en": "The Empress",
        "name_tr": "İmparatoriçe",
        "meaning_upright_en": "Femininity, beauty, nature, nurturing, abundance.",
        "meaning_upright_tr": "Dişilik, güzellik, doğa, besleyicilik, bolluk.",
        "meaning_reversed_en": "Creative block, dependence on others.",
        "meaning_reversed_tr": "Yaratıcı tıkanıklık, başkalarına bağımlılık.",
        "element": "Earth",
        "color": "#4CAF50"
    },
    {
        "id": "emperor",
        "name_en": "The Emperor",
        "name_tr": "İmparator",
        "meaning_upright_en": "Authority, establishment, structure, a father figure.",
        "meaning_upright_tr": "Otorite, düzen, yapı, baba figürü.",
        "meaning_reversed_en": "Domination, excessive control, lack of discipline.",
        "meaning_reversed_tr": "Tahakküm, aşırı kontrol, disiplinsizlik.",
        "element": "Fire",
        "color": "#F44336"
    },
    {
        "id": "hierophant",
        "name_en": "The Hierophant",
        "name_tr": "Aziz",
        "meaning_upright_en": "Spiritual wisdom, religious beliefs, conformity, tradition.",
        "meaning_upright_tr": "Ruhsal bilgelik, dini inançlar, uyum, gelenek.",
        "meaning_reversed_en": "Personal beliefs, freedom, challenging the status quo.",
        "meaning_reversed_tr": "Kişisel inançlar, özgürlük, statükoya meydan okuma.",
        "element": "Earth",
        "color": "#795548"
    },
    {
        "id": "lovers",
        "name_en": "The Lovers",
        "name_tr": "Aşıklar",
        "meaning_upright_en": "Love, harmony, relationships, values alignment, choices.",
        "meaning_upright_tr": "Aşk, uyum, ilişkiler, değerlerin örtüşmesi, seçimler.",
        "meaning_reversed_en": "Self-love, disharmony, imbalance, misalignment of values.",
        "meaning_reversed_tr": "Öz sevgi, uyumsuzluk, dengesizlik, değer çatışması.",
        "element": "Air",
        "color": "#E91E63"
    },
    {
        "id": "chariot",
        "name_en": "The Chariot",
        "name_tr": "Savaş Arabası",
        "meaning_upright_en": "Control, willpower, success, action, determination.",
        "meaning_upright_tr": "Kontrol, irade, başarı, eylem, kararlılık.",
        "meaning_reversed_en": "Self-discipline, opposition, lack of direction.",
        "meaning_reversed_tr": "Öz disiplin eksikliği, muhalefet, yönsüzlük.",
        "element": "Water",
        "color": "#FFC107"
    },
    {
        "id": "strength",
        "name_en": "Strength",
        "name_tr": "Güç",
        "meaning_upright_en": "Strength, courage, persuasion, influence, compassion.",
        "meaning_upright_tr": "Güç, cesaret, ikna, etki, şefkat.",
        "meaning_reversed_en": "Inner strength, self-doubt, low energy, raw emotion.",
        "meaning_reversed_tr": "İçsel zayıflık, kendine güvensizlik, düşük enerji.",
        "element": "Fire",
        "color": "#FF5722"
    },
    {
        "id": "hermit",
        "name_en": "The Hermit",
        "name_tr": "Ermiş",
        "meaning_upright_en": "Soul-searching, introspection, being alone, inner guidance.",
        "meaning_upright_tr": "İçsel arayış, içe bakış, yalnızlık, iç rehberlik.",
        "meaning_reversed_en": "Isolation, loneliness, withdrawal.",
        "meaning_reversed_tr": "İzolasyon, yalnızlık, geri çekilme.",
        "element": "Earth",
        "color": "#607D8B"
    },
    {
        "id": "wheel_of_fortune",
        "name_en": "Wheel of Fortune",
        "name_tr": "Kader Çarkı",
        "meaning_upright_en": "Good luck, karma, life cycles, destiny, a turning point.",
        "meaning_upright_tr": "İyi şans, karma, yaşam döngüleri, kader, dönüm noktası.",
        "meaning_reversed_en": "Bad luck, resistance to change, breaking cycles.",
        "meaning_reversed_tr": "Kötü şans, değişime direnç, döngüleri kırma.",
        "element": "Fire",
        "color": "#9C27B0"
    },
    {
        "id": "justice",
        "name_en": "Justice",
        "name_tr": "Adalet",
        "meaning_upright_en": "Justice, fairness, truth, cause and effect, law.",
        "meaning_upright_tr": "Adalet, hakkaniyet, gerçek, sebep-sonuç, yasa.",
        "meaning_reversed_en": "Unfairness, lack of accountability, dishonesty.",
        "meaning_reversed_tr": "Haksızlık, hesap verebilirlik eksikliği, dürüst olmama.",
        "element": "Air",
        "color": "#009688"
    },
    {
        "id": "hanged_man",
        "name_en": "The Hanged Man",
        "name_tr": "Asılan Adam",
        "meaning_upright_en": "Pause, surrender, letting go, new perspectives.",
        "meaning_upright_tr": "Duraklama, teslimiyet, bırakma, yeni bakış açıları.",
        "meaning_reversed_en": "Delays, resistance, stalling, indecision.",
        "meaning_reversed_tr": "Gecikmeler, direnç, oyalama, kararsızlık.",
        "element": "Water",
        "color": "#3F51B5"
    },
    {
        "id": "death",
        "name_en": "Death",
        "name_tr": "Ölüm",
        "meaning_upright_en": "Endings, change, transformation, transition.",
        "meaning_upright_tr": "Bitişler, değişim, dönüşüm, geçiş.",
        "meaning_reversed_en": "Resistance to change, personal transformation, inner purging.",
        "meaning_reversed_tr": "Değişime direnç, kişisel dönüşüm, içsel arınma.",
        "element": "Water",
        "color": "#000000"
    },
    {
        "id": "temperance",
        "name_en": "Temperance",
        "name_tr": "Denge",
        "meaning_upright_en": "Balance, moderation, patience, purpose.",
        "meaning_upright_tr": "Denge, ölçülülük, sabır, amaç.",
        "meaning_reversed_en": "Imbalance, excess, self-healing, re-alignment.",
        "meaning_reversed_tr": "Dengesizlik, aşırılık, kendini iyileştirme.",
        "element": "Fire",
        "color": "#FF9800"
    },
    {
        "id": "devil",
        "name_en": "The Devil",
        "name_tr": "Şeytan",
        "meaning_upright_en": "Shadow self, attachment, addiction, restriction, sexuality.",
        "meaning_upright_tr": "Gölge benlik, bağımlılık, kısıtlama, cinsellik.",
        "meaning_reversed_en": "Releasing limiting beliefs, exploring dark thoughts, detachment.",
        "meaning_reversed_tr": "Sınırlayıcı inançları bırakma, karanlık düşünceleri keşfetme.",
        "element": "Earth",
        "color": "#3E2723"
    },
    {
        "id": "tower",
        "name_en": "The Tower",
        "name_tr": "Yıkılan Kule",
        "meaning_upright_en": "Sudden change, upheaval, chaos, revelation, awakening.",
        "meaning_upright_tr": "Ani değişim, kargaşa, kaos, aydınlanma, uyanış.",
        "meaning_reversed_en": "Personal transformation, fear of change, averting disaster.",
        "meaning_reversed_tr": "Kişisel dönüşüm, değişim korkusu, felaketi önleme.",
        "element": "Fire",
        "color": "#B71C1C"
    },
    {
        "id": "star",
        "name_en": "The Star",
        "name_tr": "Yıldız",
        "meaning_upright_en": "Hope, faith, purpose, renewal, spirituality.",
        "meaning_upright_tr": "Umut, inanç, amaç, yenilenme, maneviyat.",
        "meaning_reversed_en": "Lack of faith, despair, self-trust, disconnection.",
        "meaning_reversed_tr": "İnançsızlık, umutsuzluk, kendine güvensizlik.",
        "element": "Air",
        "color": "#00BCD4"
    },
    {
        "id": "moon",
        "name_en": "The Moon",
        "name_tr": "Ay",
        "meaning_upright_en": "Illusion, fear, anxiety, subconscious, intuition.",
        "meaning_upright_tr": "İllüzyon, korku, endişe, bilinçaltı, sezgi.",
        "meaning_reversed_en": "Release of fear, repressed emotion, inner confusion.",
        "meaning_reversed_tr": "Korkunun serbest bırakılması, bastırılmış duygu.",
        "element": "Water",
        "color": "#673AB7"
    },
    {
        "id": "sun",
        "name_en": "The Sun",
        "name_tr": "Güneş",
        "meaning_upright_en": "Positivity, fun, warmth, success, vitality.",
        "meaning_upright_tr": "Pozitiflik, eğlence, sıcaklık, başarı, canlılık.",
        "meaning_reversed_en": "Inner child, feeling down, overly optimistic.",
        "meaning_reversed_tr": "İç çocuk, moralsizlik, aşırı iyimserlik.",
        "element": "Fire",
        "color": "#FFEB3B"
    },
    {
        "id": "judgement",
        "name_en": "Judgement",
        "name_tr": "Mahkeme",
        "meaning_upright_en": "Judgement, rebirth, inner calling, absolution.",
        "meaning_upright_tr": "Yargı, yeniden doğuş, içsel çağrı, affedilme.",
        "meaning_reversed_en": "Self-doubt, inner critic, ignoring the call.",
        "meaning_reversed_tr": "Kendine güvensizlik, içsel eleştirmen, çağrıyı görmezden gelme.",
        "element": "Fire",
        "color": "#FF5722"
    },
    {
        "id": "world",
        "name_en": "The World",
        "name_tr": "Dünya",
        "meaning_upright_en": "Completion, integration, accomplishment, travel.",
        "meaning_upright_tr": "Tamamlanma, bütünleşme, başarı, seyahat.",
        "meaning_reversed_en": "Seeking personal closure, short-cuts, delays.",
        "meaning_reversed_tr": "Kişisel kapanış arayışı, kestirmeler, gecikmeler.",
        "element": "Earth",
        "color": "#4CAF50"
    }
]
